"""initial schema

Revision ID: 365396082de6
Revises: 
Create Date: 2026-07-22 11:03:21.317866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '365396082de6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('river_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('long', sa.Float(), nullable=True),
    sa.Column('types', sa.JSON(), nullable=True),
    sa.Column('statuses', sa.JSON(), nullable=True),
    sa.Column('measure_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stations_river_name'), 'stations', ['river_name'], unique=False)
    op.create_table('readings',
    sa.Column('measure_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('quality', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('station_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parameter', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('period_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('value_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('unit_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('measure_id', 'date_time')
    )
    op.create_index(op.f('ix_readings_parameter'), 'readings', ['parameter'], unique=False)
    op.create_index(op.f('ix_readings_station_id'), 'readings', ['station_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_readings_station_id'), table_name='readings')
    op.drop_index(op.f('ix_readings_parameter'), table_name='readings')
    op.drop_table('readings')
    op.drop_index(op.f('ix_stations_river_name'), table_name='stations')
    op.drop_table('stations')
    # ### end Alembic commands ###
