"""add river_links table with postgis

Revision ID: 4c898f4c3d79
Revises: a3f0fe7b4adf
Create Date: 2026-07-22 12:33:02.219092

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4c898f4c3d79'
down_revision: Union[str, Sequence[str], None] = 'a3f0fe7b4adf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('river_links',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('watercourse_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('watercourse_name_alternative', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('form', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('flow_direction', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fictitious', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('start_node', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('end_node', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # geoalchemy2's Geometry column (spatial_index=True by default) creates its own GIST index
    # via a DDL event on table creation, so an explicit `idx_river_links_geometry` here would
    # collide with it.
    op.create_index(op.f('ix_river_links_watercourse_name'), 'river_links', ['watercourse_name'], unique=False)
    op.create_index(op.f('ix_river_links_watercourse_name_alternative'), 'river_links', ['watercourse_name_alternative'], unique=False)
    # ### end Alembic commands ###

    # `watercourse_name` alone misses reaches tagged only via `watercourse_name_alternative`
    # (see `wxdecide.schemas.rivers`), so the "give me the Thames" query needs both.
    op.execute(
        """
        CREATE VIEW river_thames AS
        SELECT * FROM river_links
        WHERE watercourse_name = 'River Thames' OR watercourse_name_alternative = 'River Thames'
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP VIEW IF EXISTS river_thames")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_river_links_watercourse_name_alternative'), table_name='river_links')
    op.drop_index(op.f('ix_river_links_watercourse_name'), table_name='river_links')
    op.drop_table('river_links')
    # ### end Alembic commands ###
