"""add nrfa station id and catchment boundaries

Revision ID: a3f0fe7b4adf
Revises: 365396082de6
Create Date: 2026-07-22 12:27:56.712362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a3f0fe7b4adf'
down_revision: Union[str, Sequence[str], None] = '365396082de6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catchment_boundaries',
    sa.Column('nrfa_station_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('area_km2', sa.Float(), nullable=False),
    sa.Column('geometry', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('nrfa_station_id')
    )
    op.add_column('stations', sa.Column('nrfa_station_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_stations_nrfa_station_id'), 'stations', ['nrfa_station_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stations_nrfa_station_id'), table_name='stations')
    op.drop_column('stations', 'nrfa_station_id')
    op.drop_table('catchment_boundaries')
    # ### end Alembic commands ###
