"""normalise station types statuses and measures

Revision ID: b8b9760994a7
Revises: 4c898f4c3d79
Create Date: 2026-07-22 12:37:39.125247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8b9760994a7'
down_revision: Union[str, Sequence[str], None] = '4c898f4c3d79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measures',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parameter', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parameter_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('period_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('value_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('unit_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('station_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measures_station_id'), 'measures', ['station_id'], unique=False)
    op.create_table('station_statuses',
    sa.Column('station_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('station_id', 'status_uri')
    )
    op.create_table('station_types',
    sa.Column('station_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('station_id', 'type_uri')
    )
    op.drop_column('stations', 'types')
    op.drop_column('stations', 'statuses')
    op.drop_column('stations', 'measure_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stations', sa.Column('measure_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('stations', sa.Column('statuses', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('stations', sa.Column('types', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_table('station_types')
    op.drop_table('station_statuses')
    op.drop_index(op.f('ix_measures_station_id'), table_name='measures')
    op.drop_table('measures')
    # ### end Alembic commands ###
