"""index river_links nodes and add connected thames view

Revision ID: f66d074397c0
Revises: b8b9760994a7
Create Date: 2026-07-22 12:51:33.929969

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'f66d074397c0'
down_revision: Union[str, Sequence[str], None] = 'b8b9760994a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Note: `spatial_ref_sys` is PostGIS' own reference table, not one of ours — autogenerate
    # flags it as "removed" because it isn't part of SQLModel.metadata, but it must never be
    # dropped.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_river_links_end_node'), 'river_links', ['end_node'], unique=False)
    op.create_index(op.f('ix_river_links_start_node'), 'river_links', ['start_node'], unique=False)
    # ### end Alembic commands ###

    # `river_thames` (see the `add river_links table with postgis` migration) only matches links
    # explicitly named "River Thames" — many real Thames links carry a local reach/pool name
    # instead (e.g. "Sonning Reach") with "River Thames" recorded only in
    # `watercourse_name_alternative`, and locks/weirs/wide tidal stretches leave short real gaps
    # in the linework even once those are included. This view starts from the named links, then
    # recursively pulls in *unnamed* links (both name fields null) no longer than
    # `max_gap_length` metres that directly bridge two already-included nodes — closing those
    # gaps without pulling in real named tributaries (which always have a different name, so
    # never match the "unnamed" recursive step). 1000m comfortably covers observed lock/weir/
    # tidal gaps on the Thames; see `nbs/02-river-geo.ipynb` for how that threshold was chosen.
    op.execute(
        """
        CREATE VIEW river_thames_connected AS
        WITH RECURSIVE named_links AS (
            SELECT id, start_node, end_node
            FROM river_links
            WHERE watercourse_name = 'River Thames'
               OR watercourse_name_alternative = 'River Thames'
        ),
        bridging(id, start_node, end_node) AS (
            SELECT rl.id, rl.start_node, rl.end_node
            FROM river_links rl
            WHERE rl.watercourse_name IS NULL
              AND rl.watercourse_name_alternative IS NULL
              AND rl.length <= 1000
              AND (
                  rl.start_node IN (SELECT start_node FROM named_links UNION SELECT end_node FROM named_links)
                  OR rl.end_node IN (SELECT start_node FROM named_links UNION SELECT end_node FROM named_links)
              )

            UNION

            SELECT rl.id, rl.start_node, rl.end_node
            FROM river_links rl
            JOIN bridging b
              ON rl.start_node IN (b.start_node, b.end_node)
              OR rl.end_node IN (b.start_node, b.end_node)
            WHERE rl.watercourse_name IS NULL
              AND rl.watercourse_name_alternative IS NULL
              AND rl.length <= 1000
        )
        SELECT rl.*
        FROM river_links rl
        WHERE rl.id IN (SELECT id FROM named_links)
           OR rl.id IN (SELECT id FROM bridging)
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP VIEW IF EXISTS river_thames_connected")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_river_links_start_node'), table_name='river_links')
    op.drop_index(op.f('ix_river_links_end_node'), table_name='river_links')
    # ### end Alembic commands ###
